# -*- coding: utf-8 -*-pack
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    # App information
    'name': 'Amazon Odoo Connector',
    'version': '12.0',
    'category': 'Sales',
    'license': 'OPL-1',
    'summary' : 'Amazon Odoo Connector helps you integrate & manage your Amazon Seller Account operations from Odoo. Save time, efforts and avoid errors due to manual data entry to boost your Amazon sales with this connector.',
    
    # Author
    'author': 'Emipro Technologies Pvt. Ltd.',
    'website': 'http://www.emiprotechnologies.com/',
    'maintainer': 'Emipro Technologies Pvt. Ltd.',
    
    # Dependencies
    'depends': ['auto_invoice_workflow_ept','common_connector_library','sale_stock'],
    
    # Views
    'data': [
             'security/res_groups.xml',
             'security/ir.model.access.csv', 
             'view/res_config_view.xml',
             'view/product_brand_view.xml',
             'view/base_browse_node.xml',
             'view/browse_node.xml',
             'view/product_view.xml',
             'view/process_import_export.xml',
             'view/sales_view.xml',
             'report/sale_report_view.xml',
             'view/order_refund_view.xml',
             'view/stock_view.xml',
             'view/invoice_view.xml',
             'view/feed_submission_history.xml',
             'view/amazon_file_process_job.xml',
             'view/amazon_report_wizard.xml',             
             'view/amazon_seller.xml',
             'view/instance_view.xml',                                                
             'view/auto_work_flow_configuration.xml',
             'view/tax_code_view.xml',
             'view/ir_cron.xml',             
             'view/product_wizard_view.xml',
             'view/cancel_order_wizard_view.xml',
             'view/res_country.xml',
             'view/web_templates.xml',
             #code comment by dhaval
             #'view/stock_quant_package.xml',
             'view/stock_warehouse.xml',
             'view/settlement_report.xml',             
             'view/amazon_transaction.xml',      
             'view/delivery.xml',
             'view/active_product_listing_view.xml',
             'view/account_fiscal_position.xml',
             'view/amazon_category.xml',
             'view/amazon_category_data.xml',
             'view/product_attribute.xml',
             'view/ir_sequence.xml',
             'view/amazon_sale_order_report_view.xml',
             'view/stock_picking_seller.xml', 
             'view/account_move_view.xml',
             'view/account_move_line_view.xml',
             'view/stock_move_view.xml',    
             'view/file_selection_wizard.xml',
             #'data/demo_data.csv',
             'data/product_data.xml',
             'data/import_product_attachment.xml',         
             'view/amazon_operations_ept_view.xml',
             #'data/amazon.base.browse.node.ept.csv',
            # 'data/amazon.uom.type.ept.csv',
            # 'data/amazon.uom.value.ept.csv',             
            # 'data/amazon.attribute.ept.csv',
             #'data/amazon.attribute.value.ept.csv',
             #'data/amazon.tax.code.ept.csv',
             #'data/amazon.cspia.warning.ept.csv',
             'data/amazon.payment.type.option.ept.csv',
             #'data/amazon.tsd.language.ept.csv',
             #'data/amazon.tsd.warning.ept.csv',
             #'data/amazon.variation.theme.ept.csv',
             #'data/amazon.transaction.type.csv',
             'data/amazon_transaction_type.xml',
             ],
    # Odoo Store Specific
    'images': ['static/description/main_screen.jpeg'],
    
    #Technical
    'installable': True,
    'auto_install': False,
    'live_test_url':'https://www.emiprotechnologies.com/free-trial?app=amazon-ept&version=12&edition=enterprise',
    'application' : True,
    'price': 430.00,
    'currency': 'EUR',
}
